language: node_js
node_js:
- "12"
services:
- docker

script:
- npm i
- npm run build
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t woodccc/sky-web:latest .
- docker push woodccc/sky-web:latest

